import type * as $Fields from './fields.js'

export * as Draft from './fields.js'

/**
* GraphQL {@link https://graphql.org/learn/schema/#object-types | Object} type.
*
* A general purpose draft. Used for comments, project updates, etc.
*
* # Info
*
* | | |
* | - | - |
* | **Kind** | {@link https://graphql.org/graphql-js/type/#graphqlobjecttype | Object ↗} |
* | **Fields** | 19 |
* | **Implements** | {@link $Schema.Node} |
*/
export interface Draft {
kind: "Object",
name: "Draft",
fields: {
__typename: $Fields.__typename,
id: $Fields.id,
createdAt: $Fields.createdAt,
updatedAt: $Fields.updatedAt,
archivedAt: $Fields.archivedAt,
bodyData: $Fields.bodyData,
data: $Fields.data,
isAutogenerated: $Fields.isAutogenerated,
wasLocalDraft: $Fields.wasLocalDraft,
user: $Fields.user,
issue: $Fields.issue,
project: $Fields.project,
projectUpdate: $Fields.projectUpdate,
initiative: $Fields.initiative,
initiativeUpdate: $Fields.initiativeUpdate,
post: $Fields.post,
parentComment: $Fields.parentComment,
customerNeed: $Fields.customerNeed,
anchor: $Fields.anchor,
team: $Fields.team
}
}