# clef-completion-digest: 2bfd45987666da6d
# Generated by sb completions
complete -c sb -e
complete -c sb -f

function __sb_exact_command
    set -l key (string join ' ' -- $argv)
    switch $key
        case 'admin community by-id'
            printf '%s\n' 'admin community by-id'
            return 0
        case 'admin community by-name'
            printf '%s\n' 'admin community by-name'
            return 0
        case 'admin community by-slug'
            printf '%s\n' 'admin community by-slug'
            return 0
        case 'admin user by-email'
            printf '%s\n' 'admin user by-email'
            return 0
        case 'admin user by-id'
            printf '%s\n' 'admin user by-id'
            return 0
        case 'admin user by-name'
            printf '%s\n' 'admin user by-name'
            return 0
        case 'authn token'
            printf '%s\n' 'authn token'
            return 0
        case 'completions install'
            printf '%s\n' 'completions install'
            return 0
        case 'completions path'
            printf '%s\n' 'completions path'
            return 0
        case 'completions print'
            printf '%s\n' 'completions print'
            return 0
        case 'eval run'
            printf '%s\n' 'eval run'
            return 0
        case 'invitation-link clear-page'
            printf '%s\n' 'invitation-link clear-page'
            return 0
        case 'invitation-link get'
            printf '%s\n' 'invitation-link get'
            return 0
        case 'invitation-link list'
            printf '%s\n' 'invitation-link list'
            return 0
        case 'invitation-link preview'
            printf '%s\n' 'invitation-link preview'
            return 0
        case 'invitation-link set-page'
            printf '%s\n' 'invitation-link set-page'
            return 0
        case 'marketing send-email'
            printf '%s\n' 'marketing send-email'
            return 0
        case 'marketing templates'
            printf '%s\n' 'marketing templates'
            return 0
        case 'observability axiom filter-snippet'
            printf '%s\n' 'observability axiom filter-snippet'
            return 0
        case 'ops tunnel airbyte'
            printf '%s\n' 'ops tunnel airbyte'
            return 0
        case 'ops tunnel db-dash'
            printf '%s\n' 'ops tunnel db-dash'
            return 0
        case 'profiling stripe-transactions'
            printf '%s\n' 'profiling stripe-transactions'
            return 0
        case 'pulse validate-actions'
            printf '%s\n' 'pulse validate-actions'
            return 0
        case 'resolve-stage'
            printf '%s\n' 'resolve-stage'
            return 0
        case 'teamspace feed'
            printf '%s\n' 'teamspace feed'
            return 0
        case 'obs axiom filter-snippet'
            printf '%s\n' 'obs axiom filter-snippet'
            return 0
    end
    return 1
end

function __sb_command_flag_takes_value
    set -l key (string join ' ' -- $argv)
    switch $key
        case 'admin community by-id::--community-id'
            return 0
        case 'admin community by-name::--name'
            return 0
        case 'admin community by-slug::--slug'
            return 0
        case 'admin user by-email::--email'
            return 0
        case 'admin user by-id::--user-id'
            return 0
        case 'admin user by-name::--name'
            return 0
        case 'authn token::--email'
            return 0
        case 'completions install::--shell'
            return 0
        case 'completions path::--shell'
            return 0
        case 'completions print::--shell'
            return 0
        case 'eval run::--model'
            return 0
        case 'eval run::--filter'
            return 0
        case 'invitation-link clear-page::--community-id'
            return 0
        case 'invitation-link clear-page::--invitation-link-id'
            return 0
        case 'invitation-link get::--community-id'
            return 0
        case 'invitation-link get::--code'
            return 0
        case 'invitation-link list::--community-id'
            return 0
        case 'invitation-link preview::--community-id'
            return 0
        case 'invitation-link set-page::--community-id'
            return 0
        case 'invitation-link set-page::--code'
            return 0
        case 'invitation-link set-page::--file'
            return 0
        case 'marketing send-email::--id'
            return 0
        case 'observability axiom filter-snippet::--format'
            return 0
        case 'ops tunnel airbyte::--key-path'
            return 0
        case 'ops tunnel airbyte::--bastion-host'
            return 0
        case 'ops tunnel airbyte::--bastion-user'
            return 0
        case 'ops tunnel airbyte::--local-port'
            return 0
        case 'ops tunnel airbyte::--remote-host'
            return 0
        case 'ops tunnel airbyte::--remote-port'
            return 0
        case 'ops tunnel db-dash::--key-path'
            return 0
        case 'ops tunnel db-dash::--bastion-host'
            return 0
        case 'ops tunnel db-dash::--bastion-user'
            return 0
        case 'ops tunnel db-dash::--local-port'
            return 0
        case 'ops tunnel db-dash::--remote-host'
            return 0
        case 'ops tunnel db-dash::--remote-port'
            return 0
        case 'profiling stripe-transactions::--community-id'
            return 0
        case 'profiling stripe-transactions::--limit'
            return 0
        case 'profiling stripe-transactions::--starting-after'
            return 0
        case 'profiling stripe-transactions::--status'
            return 0
        case 'profiling stripe-transactions::--customer-id'
            return 0
        case 'profiling stripe-transactions::--created-from'
            return 0
        case 'profiling stripe-transactions::--created-to'
            return 0
        case 'profiling stripe-transactions::--amount-currency'
            return 0
        case 'profiling stripe-transactions::--amount-min'
            return 0
        case 'profiling stripe-transactions::--amount-max'
            return 0
        case 'profiling stripe-transactions::--related-purchase-type'
            return 0
        case 'profiling stripe-transactions::--offer-id'
            return 0
        case 'profiling stripe-transactions::--event-id'
            return 0
        case 'profiling stripe-transactions::--ticket-id'
            return 0
        case 'profiling stripe-transactions::--repeat'
            return 0
        case 'profiling stripe-transactions::--warmup'
            return 0
        case 'pulse validate-actions::--community-id'
            return 0
        case 'pulse validate-actions::--user-id'
            return 0
        case 'resolve-stage::--spec'
            return 0
        case 'teamspace feed::--limit'
            return 0
        case 'teamspace feed::--cursor'
            return 0
        case 'obs axiom filter-snippet::--format'
            return 0
    end
    return 1
end

function __sb_global_flag_takes_value
    set -l key (string join ' ' -- $argv)
    switch $key
        case '--stage'
            return 0
    end
    return 1
end

function __sb_words
    set -l tokens (commandline -opc)
    if test (count $tokens) -eq 0
        return 0
    end
    set -e tokens[1]
    set -l words
    set -l i 1
    while test $i -le (count $tokens)
        set -l token $tokens[$i]
        if string match -q -- '--*' $token
            if __sb_global_flag_takes_value $token
                set -l next_index (math $i + 1)
                if test $next_index -le (count $tokens); and not string match -q -- '-*' $tokens[$next_index]
                    set i (math $i + 2)
                else
                    set i (math $i + 1)
                end
                continue
            end
            set -l command (__sb_exact_command $words)
            if test -n "$command"; and __sb_command_flag_takes_value "$command::$token"
                set -l next_index (math $i + 1)
                if test $next_index -le (count $tokens); and not string match -q -- '-*' $tokens[$next_index]
                    set i (math $i + 2)
                else
                    set i (math $i + 1)
                end
                continue
            end
            set i (math $i + 1)
            continue
        end
        if string match -q -- '-*' $token
            set i (math $i + 1)
            continue
        end
        set -a words $token
        set i (math $i + 1)
    end
    printf '%s\n' $words
end

function __sb_depth_is
    set -l depth $argv[1]
    set -l words (__sb_words)
    test (count $words) -eq $depth
end

function __sb_path_is
    set -l words (__sb_words)
    set -l expected $argv
    for i in (seq (count $expected))
        test $i -le (count $words); or return 1
        test "$words[$i]" = "$expected[$i]"; or return 1
    end
    return 0
end

complete -c sb -n 'true' -l stage -r -d 'Target stage: development (default), production'
complete -c sb -n 'true' -l sleep -d 'Keep process alive after execution (for debugging)'
complete -c sb -n 'true' -s h -l help -d 'Show help'
complete -c sb -n '__sb_depth_is 0' -a 'admin	Admin lookup helpers'
complete -c sb -n '__sb_depth_is 0' -a 'authn'
complete -c sb -n '__sb_depth_is 0' -a 'completions'
complete -c sb -n '__sb_depth_is 0' -a 'eval'
complete -c sb -n '__sb_depth_is 0' -a 'invitation-link'
complete -c sb -n '__sb_depth_is 0' -a 'marketing'
complete -c sb -n '__sb_depth_is 0' -a 'obs	Observability helpers'
complete -c sb -n '__sb_depth_is 0' -a 'observability	Observability helpers'
complete -c sb -n '__sb_depth_is 0' -a 'ops	Operational helpers'
complete -c sb -n '__sb_depth_is 0' -a 'ots	Run script (83 available)'
complete -c sb -n '__sb_depth_is 0' -a 'profiling	Production-safe profiling helpers'
complete -c sb -n '__sb_depth_is 0' -a 'pulse'
complete -c sb -n '__sb_depth_is 0' -a 'resolve-stage	Resolve a stage specifier to concrete URLs and connection info.'
complete -c sb -n '__sb_depth_is 0' -a 'teamspace'
complete -c sb -n '__sb_depth_is 0' -a 'testing	Run testing procedures and scenario helpers.'
complete -c sb -n '__sb_path_is admin; and __sb_depth_is 1' -a 'community	Admin community lookup helpers'
complete -c sb -n '__sb_path_is admin; and __sb_depth_is 1' -a 'user	Admin user lookup helpers'
complete -c sb -n '__sb_path_is admin community; and __sb_depth_is 2' -a 'by-id	Find a community by ID.'
complete -c sb -n '__sb_path_is admin community; and __sb_depth_is 2' -a 'by-name	Find communities by name substring.'
complete -c sb -n '__sb_path_is admin community; and __sb_depth_is 2' -a 'by-slug	Find communities by slug substring.'
complete -c sb -n '__sb_path_is admin user; and __sb_depth_is 2' -a 'by-email	Find users by email or auth email.'
complete -c sb -n '__sb_path_is admin user; and __sb_depth_is 2' -a 'by-id	Find a user by ID.'
complete -c sb -n '__sb_path_is admin user; and __sb_depth_is 2' -a 'by-name	Find users by name substring.'
complete -c sb -n '__sb_path_is authn; and __sb_depth_is 1' -a 'token	Mint a JWT token for a test user.'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'install	Install the managed completion script for a shell'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'path	Print the managed completion install path for a shell'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'print	Print the generated completion script for a shell'
complete -c sb -n '__sb_path_is eval; and __sb_depth_is 1' -a 'run	Run the Braintrust eval suite against a configured model.'
complete -c sb -n '__sb_path_is invitation-link; and __sb_depth_is 1' -a 'clear-page	Clear a custom page from an invitation link.'
complete -c sb -n '__sb_path_is invitation-link; and __sb_depth_is 1' -a 'get	Get invitation link details.'
complete -c sb -n '__sb_path_is invitation-link; and __sb_depth_is 1' -a 'list	List invitation links for a community.'
complete -c sb -n '__sb_path_is invitation-link; and __sb_depth_is 1' -a 'preview	Open the preview URL for a sign-up page.'
complete -c sb -n '__sb_path_is invitation-link; and __sb_depth_is 1' -a 'set-page	Set a custom page on invitation links from a file.'
complete -c sb -n '__sb_path_is marketing; and __sb_depth_is 1' -a 'send-email	Send a marketing email by ID.'
complete -c sb -n '__sb_path_is marketing; and __sb_depth_is 1' -a 'templates	List Postmark marketing email templates.'
complete -c sb -n '__sb_path_is obs; and __sb_depth_is 1' -a 'axiom'
complete -c sb -n '__sb_path_is obs axiom; and __sb_depth_is 2' -a 'filter-snippet	Print the Axiom expanded-row filter helper to stdout.'
complete -c sb -n '__sb_path_is observability; and __sb_depth_is 1' -a 'axiom'
complete -c sb -n '__sb_path_is observability axiom; and __sb_depth_is 2' -a 'filter-snippet	Print the Axiom expanded-row filter helper to stdout.'
complete -c sb -n '__sb_path_is ops; and __sb_depth_is 1' -a 'tunnel	SSH tunnel helpers'
complete -c sb -n '__sb_path_is ops tunnel; and __sb_depth_is 2' -a 'airbyte	Open an SSH tunnel through the Heartbeat bastion.'
complete -c sb -n '__sb_path_is ops tunnel; and __sb_depth_is 2' -a 'db-dash	Open an SSH tunnel through the Heartbeat bastion.'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'addNewPermission	Add New Permission'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'adjustFeedAlgo	Adjust Feed Algo'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'auditRichDocuments	Audit Rich Documents'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'backfillHubspotCreatorAssociation	Backfill Hubspot Creator Association'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'backfillWhitelabelAppIcons	Backfill Whitelabel App Icons'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'calcAndroidStats	Calc Android Stats'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'calculateInvestorNumbers	Calculate Investor Numbers'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'clickhouse.backfillCommentReactionEvents	Clickhouse Backfill Comment Reaction Events'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'clickhouse.backfillReactionRecipients	Clickhouse Backfill Reaction Recipients'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'clickhouse.backfillWikiCommentReactionEvents	Clickhouse Backfill Wiki Comment Reaction Events'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'clickhouse.memberAnalyticsTest	Clickhouse Member Analytics Test'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'communityContacts.backfill	Community Contacts Backfill'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'communityContacts.backfill.test	Community Contacts Backfill Test'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'communityContacts.backfillJourneyEngagement	Community Contacts Backfill Journey Engagement'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'communityContacts.compareLegacyLeads	Community Contacts Compare Legacy Leads'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'communityContacts.validateBackfillQueries	Community Contacts Validate Backfill Queries'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'communityEmailServer.backfill	Community Email Server Backfill'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'configureTestPaidResource	Configure Test Paid Resource'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'createMacrosInZendesk	Create Macros In Zendesk'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'createZendeskRedirects	Create Zendesk Redirects'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'customerResearch.trigger	Customer Research Trigger'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'daytona.ensureAgentSnapshots	Daytona Ensure Agent Snapshots'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'daytona.spin	Daytona Spin'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'debugCommunityUtf8	Debug Community Utf8'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'deleteSunshineUser	Delete Sunshine User'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'dm.clear	DM Clear'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'dm.seed	DM Seed'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'entitlements.backfillGrandfathered	Entitlements Backfill Grandfathered'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'entitlements.backfillNewBooleans	Entitlements Backfill New Booleans'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'entitlements.backfillNumCustomPages	Entitlements Backfill Num Custom Pages'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'exportSpotifyLinks	Export Spotify Links'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'exportTrials	Export Trials'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getGroupUsageData	Get Group Usage Data'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getHearthCommunities	Get Hearth Communities'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getNumUsers	Get Num Users'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'groups.compareReactionMemberships	Groups Compare Reaction Memberships'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'hea4881.resyncOffer	Hea4881 Resync Offer'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'hearth.dm-spam-backtest	Hearth DM Spam Backtest'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'hubspot.auditActiveCommunities	Hubspot Audit Active Communities'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'importTemplates	Import Templates'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'listPrivateChats.debug	List Private Chats Debug'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'memberDetails.seedKitchenSink	Member Details Seed Kitchen Sink'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'mobileUsageStats	Mobile Usage Stats'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'offer.backfillDefaultPrice	Offer Backfill Default Price'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'page.createTemplate	Page Create Template'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'page.migrateSlotValueBindingSchema	Page Migrate Slot Value Binding Schema'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'partnerStackCoupon.resolve	Partner Stack Coupon Resolve'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'partnerStackCoupon.seedBaseline	Partner Stack Coupon Seed Baseline'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'preserveCommunityPaymentData	Preserve Community Payment Data'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'promoteTestFlightBuild	Promote Test Flight Build'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.memory-cleanup	Pulse Memory Cleanup'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.template-gen	Pulse Template Gen'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'renameQAOffers	Rename QAOffers'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'repl	REPL'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'resources.classifyWikiMigrations	Resources Classify Wiki Migrations'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'resources.inspectStaleMigrationPreparation	Resources Inspect Stale Migration Preparation'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'resources.migrateWikiToResources	Resources Migrate Wiki To Resources'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'resources.previewAiWikiMigration	Resources Preview Ai Wiki Migration'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'resources.previewWikiMigration	Resources Preview Wiki Migration'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'resources.reviewAiWikiMigrations	Resources Review Ai Wiki Migrations'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'resources.rollbackWikiMigration	Resources Rollback Wiki Migration'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'runIntercomAnalysis	Run Intercom Analysis'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedCommunityContent	Seed Community Content'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedE2EPurchasesAndTickets	Seed E2 EPurchases And Tickets'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedHugeCommunity	Seed Huge Community'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedInAppWalkthrough	Seed In App Walkthrough'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedMobileResourceFixtures	Seed Mobile Resource Fixtures'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedPaidResources	Seed Paid Resources'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedResourcesWelcomeWalkthrough	Seed Resources Welcome Walkthrough'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedStripeTransactionsFixture	Seed Stripe Transactions Fixture'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'sendManualNotification	Send Manual Notification'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'setCommunityTierGrowth	Set Community Tier Growth'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'setSendblueWebhook	Set Sendblue Webhook'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'testEmailTemplates	Test Email Templates'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'transferEventData	Transfer Event Data'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'turbopuffer.backfillCommunity	Turbopuffer Backfill Community'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'turbopuffer.deleteNamespace	Turbopuffer Delete Namespace'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'turbopuffer.inspectRanking	Turbopuffer Inspect Ranking'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'turbopuffer.inspectSearchRows	Turbopuffer Inspect Search Rows'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'typesense.ensureWikiPostParentFields	Typesense Ensure Wiki Post Parent Fields'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'typesense.reindexUsers	Typesense Reindex Users'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updatePinnedPosts	Update Pinned Posts'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updateVideoTranscripts	Update Video Transcripts'
complete -c sb -n '__sb_path_is profiling; and __sb_depth_is 1' -a 'stripe-transactions	Profile adminPaymentsService.listStripeTransactions latency.'
complete -c sb -n '__sb_path_is pulse; and __sb_depth_is 1' -a 'validate-actions	Validate a hardcoded suggested action set against pulseToolValidation.'
complete -c sb -n '__sb_path_is teamspace; and __sb_depth_is 1' -a 'feed	Fetch threads and comments from Teamspace.'
complete -c sb -n '__sb_path_is admin community by-id; and __sb_depth_is 3' -l community-id -r -d 'Community ID to look up.'
complete -c sb -n '__sb_path_is admin community by-name; and __sb_depth_is 3' -l name -r -d 'Community name substring to search for.'
complete -c sb -n '__sb_path_is admin community by-slug; and __sb_depth_is 3' -l slug -r -d 'Community slug substring to search for.'
complete -c sb -n '__sb_path_is admin user by-email; and __sb_depth_is 3' -l email -r -d 'Email address to look up.'
complete -c sb -n '__sb_path_is admin user by-id; and __sb_depth_is 3' -l user-id -r -d 'User ID to look up.'
complete -c sb -n '__sb_path_is admin user by-name; and __sb_depth_is 3' -l name -r -d 'User name substring to search for.'
complete -c sb -n '__sb_path_is authn token; and __sb_depth_is 2' -l email -r -d 'Email of the test user to mint a JWT for'
complete -c sb -n '__sb_path_is completions install; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is completions path; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is completions print; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is eval run; and __sb_depth_is 2' -l model -x -a 'sonnet-4
sonnet-4.6' -d 'Model to run the eval against'
complete -c sb -n '__sb_path_is eval run; and __sb_depth_is 2' -l filter -r -d 'Case-insensitive substring filter on eval case name'
complete -c sb -n '__sb_path_is invitation-link clear-page; and __sb_depth_is 2' -l community-id -r -d 'Community ID (default: dev community)'
complete -c sb -n '__sb_path_is invitation-link clear-page; and __sb_depth_is 2' -l invitation-link-id -r -d 'Invitation link ID to clear'
complete -c sb -n '__sb_path_is invitation-link get; and __sb_depth_is 2' -l community-id -r -d 'Community ID (default: dev community)'
complete -c sb -n '__sb_path_is invitation-link get; and __sb_depth_is 2' -l code -r -d 'Invitation link code (default: first landing-page link)'
complete -c sb -n '__sb_path_is invitation-link list; and __sb_depth_is 2' -l community-id -r -d 'Community ID (default: dev community)'
complete -c sb -n '__sb_path_is invitation-link preview; and __sb_depth_is 2' -l community-id -r -d 'Community ID (default: dev community)'
complete -c sb -n '__sb_path_is invitation-link set-page; and __sb_depth_is 2' -l community-id -r -d 'Community ID (default: dev community)'
complete -c sb -n '__sb_path_is invitation-link set-page; and __sb_depth_is 2' -l code -r -d 'Invitation link code (default: first landing-page link)'
complete -c sb -n '__sb_path_is invitation-link set-page; and __sb_depth_is 2' -l file -r -d 'Path to the HTML template file'
complete -c sb -n '__sb_path_is marketing send-email; and __sb_depth_is 2' -l id -r -d 'The MarketingEmail ID to send'
complete -c sb -n '__sb_path_is observability axiom filter-snippet; and __sb_depth_is 3' -l format -x -a 'raw
bookmarklet' -d 'Output format for the Axiom filter helper.'
complete -c sb -n '__sb_path_is ops tunnel airbyte; and __sb_depth_is 3' -l key-path -r -d 'SSH private key path. Can also be set with HB_BASTION_KEY_PATH.'
complete -c sb -n '__sb_path_is ops tunnel airbyte; and __sb_depth_is 3' -l bastion-host -r -d 'Bastion host to connect through. Set with HB_BASTION_HOST (no default host).'
complete -c sb -n '__sb_path_is ops tunnel airbyte; and __sb_depth_is 3' -l bastion-user -r -d 'SSH user for the bastion host.'
complete -c sb -n '__sb_path_is ops tunnel airbyte; and __sb_depth_is 3' -l local-port -r -d 'Local port to bind.'
complete -c sb -n '__sb_path_is ops tunnel airbyte; and __sb_depth_is 3' -l remote-host -r -d 'Remote host reachable from the bastion.'
complete -c sb -n '__sb_path_is ops tunnel airbyte; and __sb_depth_is 3' -l remote-port -r -d 'Remote port reachable from the bastion.'
complete -c sb -n '__sb_path_is ops tunnel db-dash; and __sb_depth_is 3' -l key-path -r -d 'SSH private key path. Can also be set with HB_BASTION_KEY_PATH.'
complete -c sb -n '__sb_path_is ops tunnel db-dash; and __sb_depth_is 3' -l bastion-host -r -d 'Bastion host to connect through. Set with HB_BASTION_HOST (no default host).'
complete -c sb -n '__sb_path_is ops tunnel db-dash; and __sb_depth_is 3' -l bastion-user -r -d 'SSH user for the bastion host.'
complete -c sb -n '__sb_path_is ops tunnel db-dash; and __sb_depth_is 3' -l local-port -r -d 'Local port to bind.'
complete -c sb -n '__sb_path_is ops tunnel db-dash; and __sb_depth_is 3' -l remote-host -r -d 'Remote host reachable from the bastion.'
complete -c sb -n '__sb_path_is ops tunnel db-dash; and __sb_depth_is 3' -l remote-port -r -d 'Remote port reachable from the bastion.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l community-id -r -d 'Community ID to profile.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l limit -r -d 'listStripeTransactions page size.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l starting-after -r -d 'Stripe search next_page cursor from a prior run.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l status -x -a 'all
succeeded
refunded
disputed
failed' -d 'Transaction status filter.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l customer-id -r -d 'Stripe customer ID filter.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l created-from -r -d 'Created-at lower bound as Unix seconds.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l created-to -r -d 'Created-at upper bound as Unix seconds.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l amount-currency -r -d 'Three-letter currency filter, e.g. usd.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l amount-min -r -d 'Minimum charge amount in minor units.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l amount-max -r -d 'Maximum charge amount in minor units.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l related-purchase-type -x -a 'offer
event-ticket' -d 'Filter by an offer or event ticket purchase source.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l offer-id -r -d 'Offer ID when relatedPurchaseType=offer.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l event-id -r -d 'Event ID when relatedPurchaseType=event-ticket.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l ticket-id -r -d 'Ticket ID when relatedPurchaseType=event-ticket.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l repeat -r -d 'Number of measured runs.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l warmup -r -d 'Warmup runs excluded from the summary.'
complete -c sb -n '__sb_path_is profiling stripe-transactions; and __sb_depth_is 2' -l print-rows -d 'Print returned row IDs and statuses.'
complete -c sb -n '__sb_path_is pulse validate-actions; and __sb_depth_is 2' -l community-id -r -d 'Community ID to validate against'
complete -c sb -n '__sb_path_is pulse validate-actions; and __sb_depth_is 2' -l user-id -r -d 'User ID to validate against'
complete -c sb -n '__sb_path_is resolve-stage; and __sb_depth_is 1' -l spec -r -d 'Stage specifier: development, production'
complete -c sb -n '__sb_path_is teamspace feed; and __sb_depth_is 2' -l limit -r -d 'Number of thread feed items to fetch.'
complete -c sb -n '__sb_path_is teamspace feed; and __sb_depth_is 2' -l cursor -r -d 'Cursor returned by a prior call.'
complete -c sb -n '__sb_path_is obs axiom filter-snippet; and __sb_depth_is 3' -l format -x -a 'raw
bookmarklet' -d 'Output format for the Axiom filter helper.'
