# clef-completion-digest: 52cc4773739b85a0
# Generated by sb completions
complete -c sb -e
complete -c sb -f

function __sb_exact_command
    set -l key (string join ' ' -- $argv)
    switch $key
        case 'authn token'
            printf '%s\n' 'authn token'
            return 0
        case 'completions install'
            printf '%s\n' 'completions install'
            return 0
        case 'completions path'
            printf '%s\n' 'completions path'
            return 0
        case 'completions print'
            printf '%s\n' 'completions print'
            return 0
        case 'marketing templates'
            printf '%s\n' 'marketing templates'
            return 0
        case 'pulse validate-actions'
            printf '%s\n' 'pulse validate-actions'
            return 0
        case 'resolve-stage'
            printf '%s\n' 'resolve-stage'
            return 0
    end
    return 1
end

function __sb_command_flag_takes_value
    set -l key (string join ' ' -- $argv)
    switch $key
        case 'authn token::--email'
            return 0
        case 'completions install::--shell'
            return 0
        case 'completions path::--shell'
            return 0
        case 'completions print::--shell'
            return 0
        case 'pulse validate-actions::--community-id'
            return 0
        case 'pulse validate-actions::--user-id'
            return 0
        case 'resolve-stage::--spec'
            return 0
    end
    return 1
end

function __sb_global_flag_takes_value
    set -l key (string join ' ' -- $argv)
    switch $key
        case '--stage'
            return 0
    end
    return 1
end

function __sb_words
    set -l tokens (commandline -opc)
    if test (count $tokens) -eq 0
        return 0
    end
    set -e tokens[1]
    set -l words
    set -l i 1
    while test $i -le (count $tokens)
        set -l token $tokens[$i]
        if string match -q -- '--*' $token
            if __sb_global_flag_takes_value $token
                set -l next_index (math $i + 1)
                if test $next_index -le (count $tokens); and not string match -q -- '-*' $tokens[$next_index]
                    set i (math $i + 2)
                else
                    set i (math $i + 1)
                end
                continue
            end
            set -l command (__sb_exact_command $words)
            if test -n "$command"; and __sb_command_flag_takes_value "$command::$token"
                set -l next_index (math $i + 1)
                if test $next_index -le (count $tokens); and not string match -q -- '-*' $tokens[$next_index]
                    set i (math $i + 2)
                else
                    set i (math $i + 1)
                end
                continue
            end
            set i (math $i + 1)
            continue
        end
        if string match -q -- '-*' $token
            set i (math $i + 1)
            continue
        end
        set -a words $token
        set i (math $i + 1)
    end
    printf '%s\n' $words
end

function __sb_depth_is
    set -l depth $argv[1]
    set -l words (__sb_words)
    test (count $words) -eq $depth
end

function __sb_path_is
    set -l words (__sb_words)
    set -l expected $argv
    for i in (seq (count $expected))
        test $i -le (count $words); or return 1
        test "$words[$i]" = "$expected[$i]"; or return 1
    end
    return 0
end

complete -c sb -n 'true' -l stage -r -d 'Target stage: development (default), preview.<pr>, production'
complete -c sb -n 'true' -l sleep -d 'Keep process alive after execution (for debugging)'
complete -c sb -n 'true' -s h -l help -d 'Show help'
complete -c sb -n '__sb_depth_is 0' -a 'authn'
complete -c sb -n '__sb_depth_is 0' -a 'completions'
complete -c sb -n '__sb_depth_is 0' -a 'marketing'
complete -c sb -n '__sb_depth_is 0' -a 'ots	Run one-time script (52 available)'
complete -c sb -n '__sb_depth_is 0' -a 'pulse'
complete -c sb -n '__sb_depth_is 0' -a 'resolve-stage	Resolve a stage specifier to concrete URLs and connection info.'
complete -c sb -n '__sb_depth_is 0' -a 'testing	Run testing procedures and scenario helpers.'
complete -c sb -n '__sb_path_is authn; and __sb_depth_is 1' -a 'token	Mint JWT tokens for test users.'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'install	Install the managed completion script for a shell'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'path	Print the managed completion install path for a shell'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'print	Print the generated completion script for a shell'
complete -c sb -n '__sb_path_is marketing; and __sb_depth_is 1' -a 'templates	List Postmark marketing email templates.'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'addNewPermission'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'adjustFeedAlgo'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'axiom.eventLoopBlocks'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'backfillHubspot'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'backfillHubspotCreatorAssociation'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'calcAndroidStats'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'calculateInvestorNumbers'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'createMacrosInZendesk'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'createZendeskRedirects'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'customDomainReport'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'daytona.spin'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'deleteApproximatedDomains'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'deleteInactiveDomains'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'deleteSunshineUser'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'dm.clear'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'dm.seed'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'endpoint.compare'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'entitlements.backfillNewBooleans'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'eval.score'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'exportSpotifyLinks'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'exportTrials'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getGroupUsageData'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getHearthCommunities'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getNumUsers'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'hubspot.communityProps'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'image.generate'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'importTemplates'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'importUsers'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'mobileUsageStats'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'notification.teamspace'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'offer.backfillDefaultPrice'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'preserveCommunityPaymentData'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'promotion.test'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.memory-cleanup'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.memory-gen'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.validatePlaceholders'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulseToolsApiKey.add'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'repl'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'runIntercomAnalysis'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedCommunityContent'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedHugeCommunity'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedLargeCommunity'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'sendManualNotification'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'setCommunityTierGrowth'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'syncCanny'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'toolCredential.decrypt'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'transferEventData'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updateApproximatedTarget'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updateApproximatedToTanstack'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updatePinnedPosts'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updateVideoTranscripts'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'userCohortAnalysis'
complete -c sb -n '__sb_path_is pulse; and __sb_depth_is 1' -a 'validate-actions	Validate a hardcoded suggested action set against pulseToolValidation.'
complete -c sb -n '__sb_path_is authn token; and __sb_depth_is 2' -l email -r -d 'Specific email to mint a token for (default: admin + member test users)'
complete -c sb -n '__sb_path_is completions install; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is completions path; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is completions print; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is pulse validate-actions; and __sb_depth_is 2' -l community-id -r -d 'Community ID to validate against'
complete -c sb -n '__sb_path_is pulse validate-actions; and __sb_depth_is 2' -l user-id -r -d 'User ID to validate against'
complete -c sb -n '__sb_path_is resolve-stage; and __sb_depth_is 1' -l spec -r -d 'Stage specifier: development, preview.<pr>, production'
