# clef-completion-digest: e6a301951f2b4c74
# Generated by sb completions
complete -c sb -e
complete -c sb -f

function __sb_exact_command
    set -l key (string join ' ' -- $argv)
    switch $key
        case 'authn token'
            printf '%s\n' 'authn token'
            return 0
        case 'completions install'
            printf '%s\n' 'completions install'
            return 0
        case 'completions path'
            printf '%s\n' 'completions path'
            return 0
        case 'completions print'
            printf '%s\n' 'completions print'
            return 0
        case 'marketing templates'
            printf '%s\n' 'marketing templates'
            return 0
        case 'pulse validate-actions'
            printf '%s\n' 'pulse validate-actions'
            return 0
        case 'resolve-stage'
            printf '%s\n' 'resolve-stage'
            return 0
    end
    return 1
end

function __sb_command_flag_takes_value
    set -l key (string join ' ' -- $argv)
    switch $key
        case 'authn token::--email'
            return 0
        case 'completions install::--shell'
            return 0
        case 'completions path::--shell'
            return 0
        case 'completions print::--shell'
            return 0
        case 'pulse validate-actions::--community-id'
            return 0
        case 'pulse validate-actions::--user-id'
            return 0
        case 'resolve-stage::--spec'
            return 0
    end
    return 1
end

function __sb_global_flag_takes_value
    set -l key (string join ' ' -- $argv)
    switch $key
        case '--stage'
            return 0
    end
    return 1
end

function __sb_words
    set -l tokens (commandline -opc)
    if test (count $tokens) -eq 0
        return 0
    end
    set -e tokens[1]
    set -l words
    set -l i 1
    while test $i -le (count $tokens)
        set -l token $tokens[$i]
        if string match -q -- '--*' $token
            if __sb_global_flag_takes_value $token
                set -l next_index (math $i + 1)
                if test $next_index -le (count $tokens); and not string match -q -- '-*' $tokens[$next_index]
                    set i (math $i + 2)
                else
                    set i (math $i + 1)
                end
                continue
            end
            set -l command (__sb_exact_command $words)
            if test -n "$command"; and __sb_command_flag_takes_value "$command::$token"
                set -l next_index (math $i + 1)
                if test $next_index -le (count $tokens); and not string match -q -- '-*' $tokens[$next_index]
                    set i (math $i + 2)
                else
                    set i (math $i + 1)
                end
                continue
            end
            set i (math $i + 1)
            continue
        end
        if string match -q -- '-*' $token
            set i (math $i + 1)
            continue
        end
        set -a words $token
        set i (math $i + 1)
    end
    printf '%s\n' $words
end

function __sb_depth_is
    set -l depth $argv[1]
    set -l words (__sb_words)
    test (count $words) -eq $depth
end

function __sb_path_is
    set -l words (__sb_words)
    set -l expected $argv
    for i in (seq (count $expected))
        test $i -le (count $words); or return 1
        test "$words[$i]" = "$expected[$i]"; or return 1
    end
    return 0
end

complete -c sb -n 'true' -l stage -r -d 'Target stage: development (default), preview.<pr>, production'
complete -c sb -n 'true' -l sleep -d 'Keep process alive after execution (for debugging)'
complete -c sb -n 'true' -s h -l help -d 'Show help'
complete -c sb -n '__sb_depth_is 0' -a 'authn'
complete -c sb -n '__sb_depth_is 0' -a 'completions'
complete -c sb -n '__sb_depth_is 0' -a 'marketing'
complete -c sb -n '__sb_depth_is 0' -a 'ots	Run script (52 available)'
complete -c sb -n '__sb_depth_is 0' -a 'pulse'
complete -c sb -n '__sb_depth_is 0' -a 'resolve-stage	Resolve a stage specifier to concrete URLs and connection info.'
complete -c sb -n '__sb_depth_is 0' -a 'testing	Run testing procedures and scenario helpers.'
complete -c sb -n '__sb_path_is authn; and __sb_depth_is 1' -a 'token	Mint JWT tokens for test users.'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'install	Install the managed completion script for a shell'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'path	Print the managed completion install path for a shell'
complete -c sb -n '__sb_path_is completions; and __sb_depth_is 1' -a 'print	Print the generated completion script for a shell'
complete -c sb -n '__sb_path_is marketing; and __sb_depth_is 1' -a 'templates	List Postmark marketing email templates.'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'addNewPermission	Add New Permission'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'adjustFeedAlgo	Adjust Feed Algo'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'axiom.eventLoopBlocks	Axiom Event Loop Blocks'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'backfillHubspot	Backfill Hubspot'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'backfillHubspotCreatorAssociation	Backfill Hubspot Creator Association'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'calcAndroidStats	Calc Android Stats'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'calculateInvestorNumbers	Calculate Investor Numbers'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'createMacrosInZendesk	Create Macros In Zendesk'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'createZendeskRedirects	Create Zendesk Redirects'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'customDomainReport	Custom Domain Report'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'daytona.spin	Daytona Spin'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'deleteApproximatedDomains	Delete Approximated Domains'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'deleteInactiveDomains	Delete Inactive Domains'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'deleteSunshineUser	Delete Sunshine User'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'dm.clear	DM Clear'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'dm.seed	DM Seed'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'endpoint.compare	Endpoint Compare'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'entitlements.backfillNewBooleans	Entitlements Backfill New Booleans'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'eval.score	Eval Score'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'exportSpotifyLinks	Export Spotify Links'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'exportTrials	Export Trials'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getGroupUsageData	Get Group Usage Data'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getHearthCommunities	Get Hearth Communities'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'getNumUsers	Get Num Users'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'hubspot.communityProps	Hubspot Community Props'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'image.generate	Image Generate'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'importTemplates	Import Templates'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'importUsers	Import Users'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'mobileUsageStats	Mobile Usage Stats'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'notification.teamspace	Notification Teamspace'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'offer.backfillDefaultPrice	Offer Backfill Default Price'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'preserveCommunityPaymentData	Preserve Community Payment Data'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'promotion.test	Promotion Test'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.memory-cleanup	Pulse Memory Cleanup'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.memory-gen	Pulse Memory Gen'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulse.validatePlaceholders	Pulse Validate Placeholders'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'pulseToolsApiKey.add	Pulse Tools API Key Add'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'repl	REPL'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'runIntercomAnalysis	Run Intercom Analysis'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedCommunityContent	Seed Community Content'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedHugeCommunity	Seed Huge Community'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'seedLargeCommunity	Seed Large Community'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'sendManualNotification	Send Manual Notification'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'setCommunityTierGrowth	Set Community Tier Growth'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'syncCanny	Sync Canny'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'toolCredential.decrypt	Tool Credential Decrypt'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'transferEventData	Transfer Event Data'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updateApproximatedTarget	Update Approximated Target'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updateApproximatedToTanstack	Update Approximated To Tanstack'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updatePinnedPosts	Update Pinned Posts'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'updateVideoTranscripts	Update Video Transcripts'
complete -c sb -n '__sb_path_is ots; and __sb_depth_is 1' -a 'userCohortAnalysis	User Cohort Analysis'
complete -c sb -n '__sb_path_is pulse; and __sb_depth_is 1' -a 'validate-actions	Validate a hardcoded suggested action set against pulseToolValidation.'
complete -c sb -n '__sb_path_is authn token; and __sb_depth_is 2' -l email -r -d 'Specific email to mint a token for (default: admin + member test users)'
complete -c sb -n '__sb_path_is completions install; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is completions path; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is completions print; and __sb_depth_is 2' -l shell -x -a 'bash
fish
zsh' -d 'Shell to target (default: current shell)'
complete -c sb -n '__sb_path_is pulse validate-actions; and __sb_depth_is 2' -l community-id -r -d 'Community ID to validate against'
complete -c sb -n '__sb_path_is pulse validate-actions; and __sb_depth_is 2' -l user-id -r -d 'User ID to validate against'
complete -c sb -n '__sb_path_is resolve-stage; and __sb_depth_is 1' -l spec -r -d 'Stage specifier: development, preview.<pr>, production'
