import type * as $Fields from './fields.js'

export * as NullableIssueFilter from './fields.js'

/**
* GraphQL {@link https://graphql.org/learn/schema/#input-types | InputObject}.
*
* Issue filtering options.
*
* # Info
*
* | | |
* | - | - |
* | **Kind** | {@link https://graphql.org/graphql-js/type/#graphqlinputobjecttype | InputObject ↗} |
* | **Fields** | 65 |
* | **All Fields Nullable** | Yes |
*/
export interface NullableIssueFilter {
kind: "InputObject",
name: "NullableIssueFilter",
isAllFieldsNullable: true,
fields: {
id: $Fields.id,
createdAt: $Fields.createdAt,
updatedAt: $Fields.updatedAt,
number: $Fields.number,
title: $Fields.title,
description: $Fields.description,
priority: $Fields.priority,
estimate: $Fields.estimate,
startedAt: $Fields.startedAt,
triagedAt: $Fields.triagedAt,
completedAt: $Fields.completedAt,
canceledAt: $Fields.canceledAt,
archivedAt: $Fields.archivedAt,
autoClosedAt: $Fields.autoClosedAt,
autoArchivedAt: $Fields.autoArchivedAt,
addedToCycleAt: $Fields.addedToCycleAt,
addedToCyclePeriod: $Fields.addedToCyclePeriod,
dueDate: $Fields.dueDate,
accumulatedStateUpdatedAt: $Fields.accumulatedStateUpdatedAt,
snoozedUntilAt: $Fields.snoozedUntilAt,
assignee: $Fields.assignee,
delegate: $Fields.delegate,
lastAppliedTemplate: $Fields.lastAppliedTemplate,
recurringIssueTemplate: $Fields.recurringIssueTemplate,
sourceMetadata: $Fields.sourceMetadata,
creator: $Fields.creator,
parent: $Fields.parent,
snoozedBy: $Fields.snoozedBy,
labels: $Fields.labels,
subscribers: $Fields.subscribers,
hasSharedUsers: $Fields.hasSharedUsers,
sharedWith: $Fields.sharedWith,
team: $Fields.team,
projectMilestone: $Fields.projectMilestone,
comments: $Fields.comments,
suggestions: $Fields.suggestions,
cycle: $Fields.cycle,
project: $Fields.project,
state: $Fields.state,
children: $Fields.children,
attachments: $Fields.attachments,
searchableContent: $Fields.searchableContent,
hasRelatedRelations: $Fields.hasRelatedRelations,
hasDuplicateRelations: $Fields.hasDuplicateRelations,
hasBlockedByRelations: $Fields.hasBlockedByRelations,
hasBlockingRelations: $Fields.hasBlockingRelations,
hasSuggestedRelatedIssues: $Fields.hasSuggestedRelatedIssues,
hasSuggestedSimilarIssues: $Fields.hasSuggestedSimilarIssues,
hasSuggestedAssignees: $Fields.hasSuggestedAssignees,
hasSuggestedProjects: $Fields.hasSuggestedProjects,
hasSuggestedLabels: $Fields.hasSuggestedLabels,
hasSuggestedTeams: $Fields.hasSuggestedTeams,
slaStatus: $Fields.slaStatus,
reactions: $Fields.reactions,
needs: $Fields.needs,
releases: $Fields.releases,
customerCount: $Fields.customerCount,
customerImportantCount: $Fields.customerImportantCount,
leadTime: $Fields.leadTime,
cycleTime: $Fields.cycleTime,
ageTime: $Fields.ageTime,
triageTime: $Fields.triageTime,
null: $Fields.null,
and: $Fields.and,
or: $Fields.or
},
type: {
id?: $Fields.id['type'],
createdAt?: $Fields.createdAt['type'],
updatedAt?: $Fields.updatedAt['type'],
number?: $Fields.number['type'],
title?: $Fields.title['type'],
description?: $Fields.description['type'],
priority?: $Fields.priority['type'],
estimate?: $Fields.estimate['type'],
startedAt?: $Fields.startedAt['type'],
triagedAt?: $Fields.triagedAt['type'],
completedAt?: $Fields.completedAt['type'],
canceledAt?: $Fields.canceledAt['type'],
archivedAt?: $Fields.archivedAt['type'],
autoClosedAt?: $Fields.autoClosedAt['type'],
autoArchivedAt?: $Fields.autoArchivedAt['type'],
addedToCycleAt?: $Fields.addedToCycleAt['type'],
addedToCyclePeriod?: $Fields.addedToCyclePeriod['type'],
dueDate?: $Fields.dueDate['type'],
accumulatedStateUpdatedAt?: $Fields.accumulatedStateUpdatedAt['type'],
snoozedUntilAt?: $Fields.snoozedUntilAt['type'],
assignee?: $Fields.assignee['type'],
delegate?: $Fields.delegate['type'],
lastAppliedTemplate?: $Fields.lastAppliedTemplate['type'],
recurringIssueTemplate?: $Fields.recurringIssueTemplate['type'],
sourceMetadata?: $Fields.sourceMetadata['type'],
creator?: $Fields.creator['type'],
parent?: $Fields.parent['type'],
snoozedBy?: $Fields.snoozedBy['type'],
labels?: $Fields.labels['type'],
subscribers?: $Fields.subscribers['type'],
hasSharedUsers?: $Fields.hasSharedUsers['type'],
sharedWith?: $Fields.sharedWith['type'],
team?: $Fields.team['type'],
projectMilestone?: $Fields.projectMilestone['type'],
comments?: $Fields.comments['type'],
suggestions?: $Fields.suggestions['type'],
cycle?: $Fields.cycle['type'],
project?: $Fields.project['type'],
state?: $Fields.state['type'],
children?: $Fields.children['type'],
attachments?: $Fields.attachments['type'],
searchableContent?: $Fields.searchableContent['type'],
hasRelatedRelations?: $Fields.hasRelatedRelations['type'],
hasDuplicateRelations?: $Fields.hasDuplicateRelations['type'],
hasBlockedByRelations?: $Fields.hasBlockedByRelations['type'],
hasBlockingRelations?: $Fields.hasBlockingRelations['type'],
hasSuggestedRelatedIssues?: $Fields.hasSuggestedRelatedIssues['type'],
hasSuggestedSimilarIssues?: $Fields.hasSuggestedSimilarIssues['type'],
hasSuggestedAssignees?: $Fields.hasSuggestedAssignees['type'],
hasSuggestedProjects?: $Fields.hasSuggestedProjects['type'],
hasSuggestedLabels?: $Fields.hasSuggestedLabels['type'],
hasSuggestedTeams?: $Fields.hasSuggestedTeams['type'],
slaStatus?: $Fields.slaStatus['type'],
reactions?: $Fields.reactions['type'],
needs?: $Fields.needs['type'],
releases?: $Fields.releases['type'],
customerCount?: $Fields.customerCount['type'],
customerImportantCount?: $Fields.customerImportantCount['type'],
leadTime?: $Fields.leadTime['type'],
cycleTime?: $Fields.cycleTime['type'],
ageTime?: $Fields.ageTime['type'],
triageTime?: $Fields.triageTime['type'],
null?: $Fields.null['type'],
and?: $Fields.and['type'],
or?: $Fields.or['type']
}
}