import type * as $Fields from './fields.js'

export * as TeamUpdateInput from './fields.js'

/**
* GraphQL {@link https://graphql.org/learn/schema/#input-types | InputObject}.
*
* # Info
*
* | | |
* | - | - |
* | **Kind** | {@link https://graphql.org/graphql-js/type/#graphqlinputobjecttype | InputObject ↗} |
* | **Fields** | 51 |
* | **All Fields Nullable** | Yes |
*/
export interface TeamUpdateInput {
kind: "InputObject",
name: "TeamUpdateInput",
isAllFieldsNullable: true,
fields: {
name: $Fields.name,
description: $Fields.description,
key: $Fields.key,
icon: $Fields.icon,
color: $Fields.color,
cyclesEnabled: $Fields.cyclesEnabled,
cycleStartDay: $Fields.cycleStartDay,
cycleDuration: $Fields.cycleDuration,
cycleCooldownTime: $Fields.cycleCooldownTime,
cycleIssueAutoAssignStarted: $Fields.cycleIssueAutoAssignStarted,
cycleIssueAutoAssignCompleted: $Fields.cycleIssueAutoAssignCompleted,
cycleLockToActive: $Fields.cycleLockToActive,
cycleEnabledStartDate: $Fields.cycleEnabledStartDate,
upcomingCycleCount: $Fields.upcomingCycleCount,
timezone: $Fields.timezone,
issueOrderingNoPriorityFirst: $Fields.issueOrderingNoPriorityFirst,
inheritIssueEstimation: $Fields.inheritIssueEstimation,
issueEstimationType: $Fields.issueEstimationType,
issueEstimationAllowZero: $Fields.issueEstimationAllowZero,
setIssueSortOrderOnStateChange: $Fields.setIssueSortOrderOnStateChange,
issueEstimationExtended: $Fields.issueEstimationExtended,
defaultIssueEstimate: $Fields.defaultIssueEstimate,
slackNewIssue: $Fields.slackNewIssue,
slackIssueComments: $Fields.slackIssueComments,
slackIssueStatuses: $Fields.slackIssueStatuses,
groupIssueHistory: $Fields.groupIssueHistory,
aiThreadSummariesEnabled: $Fields.aiThreadSummariesEnabled,
aiDiscussionSummariesEnabled: $Fields.aiDiscussionSummariesEnabled,
defaultTemplateForMembersId: $Fields.defaultTemplateForMembersId,
defaultTemplateForNonMembersId: $Fields.defaultTemplateForNonMembersId,
defaultProjectTemplateId: $Fields.defaultProjectTemplateId,
private: $Fields.private,
triageEnabled: $Fields.triageEnabled,
requirePriorityToLeaveTriage: $Fields.requirePriorityToLeaveTriage,
defaultIssueStateId: $Fields.defaultIssueStateId,
autoClosePeriod: $Fields.autoClosePeriod,
autoCloseStateId: $Fields.autoCloseStateId,
autoCloseParentIssues: $Fields.autoCloseParentIssues,
autoCloseChildIssues: $Fields.autoCloseChildIssues,
autoArchivePeriod: $Fields.autoArchivePeriod,
markedAsDuplicateWorkflowStateId: $Fields.markedAsDuplicateWorkflowStateId,
joinByDefault: $Fields.joinByDefault,
scimManaged: $Fields.scimManaged,
parentId: $Fields.parentId,
inheritWorkflowStatuses: $Fields.inheritWorkflowStatuses,
inheritProductIntelligenceScope: $Fields.inheritProductIntelligenceScope,
productIntelligenceScope: $Fields.productIntelligenceScope,
securitySettings: $Fields.securitySettings,
allMembersCanJoin: $Fields.allMembersCanJoin,
retiredAt: $Fields.retiredAt,
handleSubTeamsOnRetirement: $Fields.handleSubTeamsOnRetirement
},
type: {
name?: $Fields.name['type'],
description?: $Fields.description['type'],
key?: $Fields.key['type'],
icon?: $Fields.icon['type'],
color?: $Fields.color['type'],
cyclesEnabled?: $Fields.cyclesEnabled['type'],
cycleStartDay?: $Fields.cycleStartDay['type'],
cycleDuration?: $Fields.cycleDuration['type'],
cycleCooldownTime?: $Fields.cycleCooldownTime['type'],
cycleIssueAutoAssignStarted?: $Fields.cycleIssueAutoAssignStarted['type'],
cycleIssueAutoAssignCompleted?: $Fields.cycleIssueAutoAssignCompleted['type'],
cycleLockToActive?: $Fields.cycleLockToActive['type'],
cycleEnabledStartDate?: $Fields.cycleEnabledStartDate['type'],
upcomingCycleCount?: $Fields.upcomingCycleCount['type'],
timezone?: $Fields.timezone['type'],
issueOrderingNoPriorityFirst?: $Fields.issueOrderingNoPriorityFirst['type'],
inheritIssueEstimation?: $Fields.inheritIssueEstimation['type'],
issueEstimationType?: $Fields.issueEstimationType['type'],
issueEstimationAllowZero?: $Fields.issueEstimationAllowZero['type'],
setIssueSortOrderOnStateChange?: $Fields.setIssueSortOrderOnStateChange['type'],
issueEstimationExtended?: $Fields.issueEstimationExtended['type'],
defaultIssueEstimate?: $Fields.defaultIssueEstimate['type'],
slackNewIssue?: $Fields.slackNewIssue['type'],
slackIssueComments?: $Fields.slackIssueComments['type'],
slackIssueStatuses?: $Fields.slackIssueStatuses['type'],
groupIssueHistory?: $Fields.groupIssueHistory['type'],
aiThreadSummariesEnabled?: $Fields.aiThreadSummariesEnabled['type'],
aiDiscussionSummariesEnabled?: $Fields.aiDiscussionSummariesEnabled['type'],
defaultTemplateForMembersId?: $Fields.defaultTemplateForMembersId['type'],
defaultTemplateForNonMembersId?: $Fields.defaultTemplateForNonMembersId['type'],
defaultProjectTemplateId?: $Fields.defaultProjectTemplateId['type'],
private?: $Fields.private['type'],
triageEnabled?: $Fields.triageEnabled['type'],
requirePriorityToLeaveTriage?: $Fields.requirePriorityToLeaveTriage['type'],
defaultIssueStateId?: $Fields.defaultIssueStateId['type'],
autoClosePeriod?: $Fields.autoClosePeriod['type'],
autoCloseStateId?: $Fields.autoCloseStateId['type'],
autoCloseParentIssues?: $Fields.autoCloseParentIssues['type'],
autoCloseChildIssues?: $Fields.autoCloseChildIssues['type'],
autoArchivePeriod?: $Fields.autoArchivePeriod['type'],
markedAsDuplicateWorkflowStateId?: $Fields.markedAsDuplicateWorkflowStateId['type'],
joinByDefault?: $Fields.joinByDefault['type'],
scimManaged?: $Fields.scimManaged['type'],
parentId?: $Fields.parentId['type'],
inheritWorkflowStatuses?: $Fields.inheritWorkflowStatuses['type'],
inheritProductIntelligenceScope?: $Fields.inheritProductIntelligenceScope['type'],
productIntelligenceScope?: $Fields.productIntelligenceScope['type'],
securitySettings?: $Fields.securitySettings['type'],
allMembersCanJoin?: $Fields.allMembersCanJoin['type'],
retiredAt?: $Fields.retiredAt['type'],
handleSubTeamsOnRetirement?: $Fields.handleSubTeamsOnRetirement['type']
}
}