import type * as $Fields from './fields.js'
import type { CustomerNotificationSubscription, User, Organization, Facet, Team, WorkflowState, Issue, Cycle, Document, Project, ProjectStatus, Template, ProjectUpdate, Reaction, Comment, DocumentContent, Initiative, InitiativeUpdate, EntityExternalLink, IntegrationsSettings, InitiativeHistory, ProjectMilestone, AiPromptRules, Post, ExternalUser, AgentSession, AgentActivity, AgentSessionToPullRequest, PullRequest, Favorite, CustomView, FeedItem, ViewPreferences, IssueLabel, ProjectLabel, Customer, CustomerStatus, CustomerTier, Integration, Dashboard, Release, ReleasePipeline, ReleaseStage, InitiativeToProject, ProjectHistory, ProjectRelation, CustomerNeed, Attachment, ProjectAttachment, IssueHistory, IssueImport, WorkflowDefinition, IssueRelation, IssueSuggestion, TriageResponsibility, TimeSchedule, TeamMembership, GitAutomationState, GitAutomationTargetBranch, Webhook, PaidSubscription, IdentityProvider, IssueDraft, Draft, CustomViewNotificationSubscription, CycleNotificationSubscription, LabelNotificationSubscription, ProjectNotificationSubscription, InitiativeNotificationSubscription, TeamNotificationSubscription, UserNotificationSubscription, IssueNotification, ProjectNotification, InitiativeNotification, OauthClientApprovalNotification, OauthClientApproval, DocumentNotification, PostNotification, CustomerNeedNotification, CustomerNotification, PullRequestNotification, UserSettings, SemanticSearchResult, DocumentSearchResult, ProjectSearchResult, IssueSearchResult, RoadmapToProject, Roadmap, OrganizationInvite, IssueToRelease, IntegrationTemplate, InitiativeRelation, Emoji, EmailIntakeAddress, SesDomainIdentity, AuditEntry, AsksWebSettings, PushSubscription, OrganizationDomain, NotificationSubscription, Entity, Notification } from '../../__.js'

export * as Node from './fields.js'

/**
* GraphQL {@link https://graphql.org/graphql-js/type/#graphqlinterfacetype | Interface}.
*
* # Info
*
* | | |
* | - | - |
* | **Kind** | {@link https://graphql.org/graphql-js/type/#graphqlinterfacetype | Interface ↗} |
* | **Fields** | 1 |
* | **Implementors** | {@link $Schema.CustomerNotificationSubscription}, {@link $Schema.User}, {@link $Schema.Organization}, {@link $Schema.Facet}, {@link $Schema.Team}, {@link $Schema.WorkflowState}, {@link $Schema.Issue}, {@link $Schema.Cycle}, {@link $Schema.Document}, {@link $Schema.Project}, {@link $Schema.ProjectStatus}, {@link $Schema.Template}, {@link $Schema.ProjectUpdate}, {@link $Schema.Reaction}, {@link $Schema.Comment}, {@link $Schema.DocumentContent}, {@link $Schema.Initiative}, {@link $Schema.InitiativeUpdate}, {@link $Schema.EntityExternalLink}, {@link $Schema.IntegrationsSettings}, {@link $Schema.InitiativeHistory}, {@link $Schema.ProjectMilestone}, {@link $Schema.AiPromptRules}, {@link $Schema.Post}, {@link $Schema.ExternalUser}, {@link $Schema.AgentSession}, {@link $Schema.AgentActivity}, {@link $Schema.AgentSessionToPullRequest}, {@link $Schema.PullRequest}, {@link $Schema.Favorite}, {@link $Schema.CustomView}, {@link $Schema.FeedItem}, {@link $Schema.ViewPreferences}, {@link $Schema.IssueLabel}, {@link $Schema.ProjectLabel}, {@link $Schema.Customer}, {@link $Schema.CustomerStatus}, {@link $Schema.CustomerTier}, {@link $Schema.Integration}, {@link $Schema.Dashboard}, {@link $Schema.Release}, {@link $Schema.ReleasePipeline}, {@link $Schema.ReleaseStage}, {@link $Schema.InitiativeToProject}, {@link $Schema.ProjectHistory}, {@link $Schema.ProjectRelation}, {@link $Schema.CustomerNeed}, {@link $Schema.Attachment}, {@link $Schema.ProjectAttachment}, {@link $Schema.IssueHistory}, {@link $Schema.IssueImport}, {@link $Schema.WorkflowDefinition}, {@link $Schema.IssueRelation}, {@link $Schema.IssueSuggestion}, {@link $Schema.TriageResponsibility}, {@link $Schema.TimeSchedule}, {@link $Schema.TeamMembership}, {@link $Schema.GitAutomationState}, {@link $Schema.GitAutomationTargetBranch}, {@link $Schema.Webhook}, {@link $Schema.PaidSubscription}, {@link $Schema.IdentityProvider}, {@link $Schema.IssueDraft}, {@link $Schema.Draft}, {@link $Schema.CustomViewNotificationSubscription}, {@link $Schema.CycleNotificationSubscription}, {@link $Schema.LabelNotificationSubscription}, {@link $Schema.ProjectNotificationSubscription}, {@link $Schema.InitiativeNotificationSubscription}, {@link $Schema.TeamNotificationSubscription}, {@link $Schema.UserNotificationSubscription}, {@link $Schema.IssueNotification}, {@link $Schema.ProjectNotification}, {@link $Schema.InitiativeNotification}, {@link $Schema.OauthClientApprovalNotification}, {@link $Schema.OauthClientApproval}, {@link $Schema.DocumentNotification}, {@link $Schema.PostNotification}, {@link $Schema.CustomerNeedNotification}, {@link $Schema.CustomerNotification}, {@link $Schema.PullRequestNotification}, {@link $Schema.UserSettings}, {@link $Schema.SemanticSearchResult}, {@link $Schema.DocumentSearchResult}, {@link $Schema.ProjectSearchResult}, {@link $Schema.IssueSearchResult}, {@link $Schema.RoadmapToProject}, {@link $Schema.Roadmap}, {@link $Schema.OrganizationInvite}, {@link $Schema.IssueToRelease}, {@link $Schema.IntegrationTemplate}, {@link $Schema.InitiativeRelation}, {@link $Schema.Emoji}, {@link $Schema.EmailIntakeAddress}, {@link $Schema.SesDomainIdentity}, {@link $Schema.AuditEntry}, {@link $Schema.AsksWebSettings}, {@link $Schema.PushSubscription}, {@link $Schema.OrganizationDomain}, {@link $Schema.NotificationSubscription}, {@link $Schema.Entity}, {@link $Schema.Notification} |
*/
export interface Node {
kind: "Interface",
name: "Node",
fields: {
__typename: $Fields.__typename,
id: $Fields.id
},
implementors: [CustomerNotificationSubscription, User, Organization, Facet, Team, WorkflowState, Issue, Cycle, Document, Project, ProjectStatus, Template, ProjectUpdate, Reaction, Comment, DocumentContent, Initiative, InitiativeUpdate, EntityExternalLink, IntegrationsSettings, InitiativeHistory, ProjectMilestone, AiPromptRules, Post, ExternalUser, AgentSession, AgentActivity, AgentSessionToPullRequest, PullRequest, Favorite, CustomView, FeedItem, ViewPreferences, IssueLabel, ProjectLabel, Customer, CustomerStatus, CustomerTier, Integration, Dashboard, Release, ReleasePipeline, ReleaseStage, InitiativeToProject, ProjectHistory, ProjectRelation, CustomerNeed, Attachment, ProjectAttachment, IssueHistory, IssueImport, WorkflowDefinition, IssueRelation, IssueSuggestion, TriageResponsibility, TimeSchedule, TeamMembership, GitAutomationState, GitAutomationTargetBranch, Webhook, PaidSubscription, IdentityProvider, IssueDraft, Draft, CustomViewNotificationSubscription, CycleNotificationSubscription, LabelNotificationSubscription, ProjectNotificationSubscription, InitiativeNotificationSubscription, TeamNotificationSubscription, UserNotificationSubscription, IssueNotification, ProjectNotification, InitiativeNotification, OauthClientApprovalNotification, OauthClientApproval, DocumentNotification, PostNotification, CustomerNeedNotification, CustomerNotification, PullRequestNotification, UserSettings, SemanticSearchResult, DocumentSearchResult, ProjectSearchResult, IssueSearchResult, RoadmapToProject, Roadmap, OrganizationInvite, IssueToRelease, IntegrationTemplate, InitiativeRelation, Emoji, EmailIntakeAddress, SesDomainIdentity, AuditEntry, AsksWebSettings, PushSubscription, OrganizationDomain, NotificationSubscription, Entity, Notification],
implementorsUnion: CustomerNotificationSubscription
| User
| Organization
| Facet
| Team
| WorkflowState
| Issue
| Cycle
| Document
| Project
| ProjectStatus
| Template
| ProjectUpdate
| Reaction
| Comment
| DocumentContent
| Initiative
| InitiativeUpdate
| EntityExternalLink
| IntegrationsSettings
| InitiativeHistory
| ProjectMilestone
| AiPromptRules
| Post
| ExternalUser
| AgentSession
| AgentActivity
| AgentSessionToPullRequest
| PullRequest
| Favorite
| CustomView
| FeedItem
| ViewPreferences
| IssueLabel
| ProjectLabel
| Customer
| CustomerStatus
| CustomerTier
| Integration
| Dashboard
| Release
| ReleasePipeline
| ReleaseStage
| InitiativeToProject
| ProjectHistory
| ProjectRelation
| CustomerNeed
| Attachment
| ProjectAttachment
| IssueHistory
| IssueImport
| WorkflowDefinition
| IssueRelation
| IssueSuggestion
| TriageResponsibility
| TimeSchedule
| TeamMembership
| GitAutomationState
| GitAutomationTargetBranch
| Webhook
| PaidSubscription
| IdentityProvider
| IssueDraft
| Draft
| CustomViewNotificationSubscription
| CycleNotificationSubscription
| LabelNotificationSubscription
| ProjectNotificationSubscription
| InitiativeNotificationSubscription
| TeamNotificationSubscription
| UserNotificationSubscription
| IssueNotification
| ProjectNotification
| InitiativeNotification
| OauthClientApprovalNotification
| OauthClientApproval
| DocumentNotification
| PostNotification
| CustomerNeedNotification
| CustomerNotification
| PullRequestNotification
| UserSettings
| SemanticSearchResult
| DocumentSearchResult
| ProjectSearchResult
| IssueSearchResult
| RoadmapToProject
| Roadmap
| OrganizationInvite
| IssueToRelease
| IntegrationTemplate
| InitiativeRelation
| Emoji
| EmailIntakeAddress
| SesDomainIdentity
| AuditEntry
| AsksWebSettings
| PushSubscription
| OrganizationDomain
| NotificationSubscription
| Entity
| Notification,
implementorsIndex: {
CustomerNotificationSubscription: CustomerNotificationSubscription,
User: User,
Organization: Organization,
Facet: Facet,
Team: Team,
WorkflowState: WorkflowState,
Issue: Issue,
Cycle: Cycle,
Document: Document,
Project: Project,
ProjectStatus: ProjectStatus,
Template: Template,
ProjectUpdate: ProjectUpdate,
Reaction: Reaction,
Comment: Comment,
DocumentContent: DocumentContent,
Initiative: Initiative,
InitiativeUpdate: InitiativeUpdate,
EntityExternalLink: EntityExternalLink,
IntegrationsSettings: IntegrationsSettings,
InitiativeHistory: InitiativeHistory,
ProjectMilestone: ProjectMilestone,
AiPromptRules: AiPromptRules,
Post: Post,
ExternalUser: ExternalUser,
AgentSession: AgentSession,
AgentActivity: AgentActivity,
AgentSessionToPullRequest: AgentSessionToPullRequest,
PullRequest: PullRequest,
Favorite: Favorite,
CustomView: CustomView,
FeedItem: FeedItem,
ViewPreferences: ViewPreferences,
IssueLabel: IssueLabel,
ProjectLabel: ProjectLabel,
Customer: Customer,
CustomerStatus: CustomerStatus,
CustomerTier: CustomerTier,
Integration: Integration,
Dashboard: Dashboard,
Release: Release,
ReleasePipeline: ReleasePipeline,
ReleaseStage: ReleaseStage,
InitiativeToProject: InitiativeToProject,
ProjectHistory: ProjectHistory,
ProjectRelation: ProjectRelation,
CustomerNeed: CustomerNeed,
Attachment: Attachment,
ProjectAttachment: ProjectAttachment,
IssueHistory: IssueHistory,
IssueImport: IssueImport,
WorkflowDefinition: WorkflowDefinition,
IssueRelation: IssueRelation,
IssueSuggestion: IssueSuggestion,
TriageResponsibility: TriageResponsibility,
TimeSchedule: TimeSchedule,
TeamMembership: TeamMembership,
GitAutomationState: GitAutomationState,
GitAutomationTargetBranch: GitAutomationTargetBranch,
Webhook: Webhook,
PaidSubscription: PaidSubscription,
IdentityProvider: IdentityProvider,
IssueDraft: IssueDraft,
Draft: Draft,
CustomViewNotificationSubscription: CustomViewNotificationSubscription,
CycleNotificationSubscription: CycleNotificationSubscription,
LabelNotificationSubscription: LabelNotificationSubscription,
ProjectNotificationSubscription: ProjectNotificationSubscription,
InitiativeNotificationSubscription: InitiativeNotificationSubscription,
TeamNotificationSubscription: TeamNotificationSubscription,
UserNotificationSubscription: UserNotificationSubscription,
IssueNotification: IssueNotification,
ProjectNotification: ProjectNotification,
InitiativeNotification: InitiativeNotification,
OauthClientApprovalNotification: OauthClientApprovalNotification,
OauthClientApproval: OauthClientApproval,
DocumentNotification: DocumentNotification,
PostNotification: PostNotification,
CustomerNeedNotification: CustomerNeedNotification,
CustomerNotification: CustomerNotification,
PullRequestNotification: PullRequestNotification,
UserSettings: UserSettings,
SemanticSearchResult: SemanticSearchResult,
DocumentSearchResult: DocumentSearchResult,
ProjectSearchResult: ProjectSearchResult,
IssueSearchResult: IssueSearchResult,
RoadmapToProject: RoadmapToProject,
Roadmap: Roadmap,
OrganizationInvite: OrganizationInvite,
IssueToRelease: IssueToRelease,
IntegrationTemplate: IntegrationTemplate,
InitiativeRelation: InitiativeRelation,
Emoji: Emoji,
EmailIntakeAddress: EmailIntakeAddress,
SesDomainIdentity: SesDomainIdentity,
AuditEntry: AuditEntry,
AsksWebSettings: AsksWebSettings,
PushSubscription: PushSubscription,
OrganizationDomain: OrganizationDomain,
NotificationSubscription: NotificationSubscription,
Entity: Entity,
Notification: Notification
}
}