import type * as $$Utilities from 'graffle/utilities-for-generated'
import type { GraphqlKit } from 'graffle/utilities-for-generated'
import type { $DefaultSelectionContext } from '../../_context.js'
import type * as $Scalars from '../../scalars/_.js'

export type * as CustomerCreateInput from './fields.js'

/**
* Input for {@link https://graphql.org/learn/schema/#input-types | InputObject}.
*
* # Info
*
* | | |
* | - | - |
* | **Kind** | {@link https://graphql.org/graphql-js/type/#graphqlinputobjecttype | InputObject ↗} |
* | **Fields** | 12 |
* | **All Fields Nullable** | Yes |
*/
export interface CustomerCreateInput<_$Context extends GraphqlKit.Document.Object.Select.SelectionContext = $DefaultSelectionContext> {
/**
* The identifier in UUID v4 format. If none is provided, the backend will generate one.
*/
id?: $Scalars.String<_$Context>,
/**
* The name of the customer.
*/
name: $Scalars.String$NonNull<_$Context>,
/**
* The domains associated with this customer.
*/
domains?: GraphqlKit.Document.Object.Var.MaybeSchemaful<Array<$Scalars.String<_$Context>> | null | undefined>,
/**
* The ids of the customers in external systems.
*/
externalIds?: GraphqlKit.Document.Object.Var.MaybeSchemaful<Array<$Scalars.String<_$Context>> | null | undefined>,
/**
* The ID of the Slack channel used to interact with the customer.
*/
slackChannelId?: $Scalars.String<_$Context>,
/**
* The user who owns the customer.
*/
ownerId?: $Scalars.String<_$Context>,
/**
* The status of the customer.
*/
statusId?: $Scalars.String<_$Context>,
/**
* The annual revenue generated by the customer.
*/
revenue?: $Scalars.Int<_$Context>,
/**
* The size of the customer.
*/
size?: $Scalars.Int<_$Context>,
/**
* The tier of the customer customer.
*/
tierId?: $Scalars.String<_$Context>,
/**
* The URL of the customer's logo.
*/
logoUrl?: $Scalars.String<_$Context>,
/**
* The main source of the customer, for customers with multiple sources. Must be one of externalIds.
*/
mainSourceId?: $Scalars.String<_$Context>
}