import type * as $Fields from './fields.js'

export * as Query from './fields.js'

/**
* GraphQL root {@link https://graphql.org/learn/schema/#the-query-and-mutation-types | Query} type.
*
* # Info
*
* | | |
* | - | - |
* | **Kind** | {@link https://graphql.org/graphql-js/type/#graphqlobjecttype | Object ↗} |
* | **Fields** | 142 |
*/
export interface Query {
kind: "Object",
name: "Query",
fields: {
__typename: $Fields.__typename,
workflowStates: $Fields.workflowStates,
workflowState: $Fields.workflowState,
webhooks: $Fields.webhooks,
webhook: $Fields.webhook,
failuresForOauthWebhooks: $Fields.failuresForOauthWebhooks,
userSettings: $Fields.userSettings,
users: $Fields.users,
user: $Fields.user,
viewer: $Fields.viewer,
userSessions: $Fields.userSessions,
triageResponsibilities: $Fields.triageResponsibilities,
triageResponsibility: $Fields.triageResponsibility,
timeSchedules: $Fields.timeSchedules,
timeSchedule: $Fields.timeSchedule,
templates: $Fields.templates,
template: $Fields.template,
templatesForIntegration: $Fields.templatesForIntegration,
projects: $Fields.projects,
project: $Fields.project,
projectFilterSuggestion: $Fields.projectFilterSuggestion,
teams: $Fields.teams,
administrableTeams: $Fields.administrableTeams,
team: $Fields.team,
teamMemberships: $Fields.teamMemberships,
teamMembership: $Fields.teamMembership,
semanticSearch: $Fields.semanticSearch,
searchDocuments: $Fields.searchDocuments,
searchProjects: $Fields.searchProjects,
searchIssues: $Fields.searchIssues,
roadmapToProjects: $Fields.roadmapToProjects,
roadmapToProject: $Fields.roadmapToProject,
roadmaps: $Fields.roadmaps,
roadmap: $Fields.roadmap,
releaseStages: $Fields.releaseStages,
releaseStage: $Fields.releaseStage,
releases: $Fields.releases,
release: $Fields.release,
releasePipelines: $Fields.releasePipelines,
releasePipeline: $Fields.releasePipeline,
rateLimitStatus: $Fields.rateLimitStatus,
pushSubscriptionTest: $Fields.pushSubscriptionTest,
projectUpdates: $Fields.projectUpdates,
projectUpdate: $Fields.projectUpdate,
projectStatuses: $Fields.projectStatuses,
projectStatusProjectCount: $Fields.projectStatusProjectCount,
projectStatus: $Fields.projectStatus,
projectRelations: $Fields.projectRelations,
projectRelation: $Fields.projectRelation,
projectMilestones: $Fields.projectMilestones,
projectMilestone: $Fields.projectMilestone,
projectLabels: $Fields.projectLabels,
projectLabel: $Fields.projectLabel,
organization: $Fields.organization,
organizationExists: $Fields.organizationExists,
archivedTeams: $Fields.archivedTeams,
organizationMeta: $Fields.organizationMeta,
organizationInvites: $Fields.organizationInvites,
organizationInvite: $Fields.organizationInvite,
organizationInviteDetails: $Fields.organizationInviteDetails,
organizationDomainClaimRequest: $Fields.organizationDomainClaimRequest,
notificationSubscriptions: $Fields.notificationSubscriptions,
notificationSubscription: $Fields.notificationSubscription,
notifications: $Fields.notifications,
notificationsUnreadCount: $Fields.notificationsUnreadCount,
notification: $Fields.notification,
issueToReleases: $Fields.issueToReleases,
issueToRelease: $Fields.issueToRelease,
issues: $Fields.issues,
issue: $Fields.issue,
issueSearch: $Fields.issueSearch,
issueVcsBranchSearch: $Fields.issueVcsBranchSearch,
issueFigmaFileKeySearch: $Fields.issueFigmaFileKeySearch,
issuePriorityValues: $Fields.issuePriorityValues,
issueFilterSuggestion: $Fields.issueFilterSuggestion,
issueRepositorySuggestions: $Fields.issueRepositorySuggestions,
issueRelations: $Fields.issueRelations,
issueRelation: $Fields.issueRelation,
issueLabels: $Fields.issueLabels,
issueLabel: $Fields.issueLabel,
issueImportCheckCSV: $Fields.issueImportCheckCSV,
issueImportCheckSync: $Fields.issueImportCheckSync,
issueImportJqlCheck: $Fields.issueImportJqlCheck,
integrationsSettings: $Fields.integrationsSettings,
integrationTemplates: $Fields.integrationTemplates,
integrationTemplate: $Fields.integrationTemplate,
integrations: $Fields.integrations,
integration: $Fields.integration,
verifyGitHubEnterpriseServerInstallation: $Fields.verifyGitHubEnterpriseServerInstallation,
integrationHasScopes: $Fields.integrationHasScopes,
initiativeUpdates: $Fields.initiativeUpdates,
initiativeUpdate: $Fields.initiativeUpdate,
initiativeToProjects: $Fields.initiativeToProjects,
initiativeToProject: $Fields.initiativeToProject,
initiatives: $Fields.initiatives,
initiative: $Fields.initiative,
initiativeRelations: $Fields.initiativeRelations,
initiativeRelation: $Fields.initiativeRelation,
fetchData: $Fields.fetchData,
favorites: $Fields.favorites,
favorite: $Fields.favorite,
externalUsers: $Fields.externalUsers,
externalUser: $Fields.externalUser,
entityExternalLink: $Fields.entityExternalLink,
emojis: $Fields.emojis,
emoji: $Fields.emoji,
emailIntakeAddress: $Fields.emailIntakeAddress,
documents: $Fields.documents,
document: $Fields.document,
documentContentHistory: $Fields.documentContentHistory,
cycles: $Fields.cycles,
cycle: $Fields.cycle,
customerTiers: $Fields.customerTiers,
customerTier: $Fields.customerTier,
customerStatuses: $Fields.customerStatuses,
customerStatus: $Fields.customerStatus,
customers: $Fields.customers,
customer: $Fields.customer,
customerNeeds: $Fields.customerNeeds,
customerNeed: $Fields.customerNeed,
issueTitleSuggestionFromCustomerRequest: $Fields.issueTitleSuggestionFromCustomerRequest,
customViews: $Fields.customViews,
customView: $Fields.customView,
customViewDetailsSuggestion: $Fields.customViewDetailsSuggestion,
customViewHasSubscribers: $Fields.customViewHasSubscribers,
comments: $Fields.comments,
comment: $Fields.comment,
availableUsers: $Fields.availableUsers,
authenticationSessions: $Fields.authenticationSessions,
ssoUrlFromEmail: $Fields.ssoUrlFromEmail,
auditEntryTypes: $Fields.auditEntryTypes,
auditEntries: $Fields.auditEntries,
attachments: $Fields.attachments,
attachment: $Fields.attachment,
attachmentsForURL: $Fields.attachmentsForURL,
attachmentIssue: $Fields.attachmentIssue,
attachmentSources: $Fields.attachmentSources,
asksWebSetting: $Fields.asksWebSetting,
applicationInfo: $Fields.applicationInfo,
agentSessions: $Fields.agentSessions,
agentSession: $Fields.agentSession,
agentActivities: $Fields.agentActivities,
agentActivity: $Fields.agentActivity
}
}